# Copyright (c) 2017, XMOS Ltd, All rights reserved

TARGET = XCORE-200-EXPLORER
USED_MODULES = lib_led_array lib_xassert lib_logging

XCC_FLAGS = -Os -g

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
