# Copyright (c) 2017, XMOS Ltd, All rights reserved

TARGET = XCORE-200-EXPLORER
USED_MODULES = lib_led_array lib_xassert lib_logging Unity

XCC_FLAGS = -Os -g -DUNITY_INCLUDE_CONFIG_H -DDEBUG_PRINT_ENABLE=1

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
